### ISSUE TITLE
I get 404s when redirecting to the pages.

### ISSUE THREAD

**Issue by Eusebiotrigo** [izoukhai/next13-internationalization-i18n-next-translate#2]
Hi!

Thanks for your guide integrating next-translate and the app folder and for your article!

I have been following it to integrate internationalization using next-translate and I am only getting 404 when trying access our application's pages. Our pages are in the /app/[lang]/(routes)/page.tsx (the home page. And yeah, I'm getting a 404 when trying to access it.

We have also Clerk (authentication) in the middle that could complicate things.

**Comment by izoukhai** [comment]
Hey,

Thank you for your kind words!
Not gonna lie, I just bumped Next away and went for Nuxt, so I won't be able to help you much 😢

Do you get 404s when you build the project locally?

**Comment by Eusebiotrigo** [comment]
So it may be related to a NextJs version... I have tried your project with 13.3.4 (the original is 13.3.1) and it works perfectly fine, but if I upgrade it to 13.4, the appRouter does not find the pages anymore. We are on 14.0.4 (latest of the... well the latest).

I'll redirect my anger to Vercel and Next 😉 

PS: You could close the issue.
